# taken from http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions
#
# Permission is granted to copy, distribute and/or modify Wikipedia's text
# under the terms of the Creative Commons Attribution-ShareAlike 3.0 Unported
# License and, unless otherwise noted, the GNU Free Documentation License.
# unversioned, with no invariant sections, front-cover texts, or back-cover texts.
# 
# https://en.wikipedia.org/wiki/Wikipedia:Copyrights

"""
Default-Access-Restriction for all countries

with "street", "track", and "service" introduced as `:yes` for all modes.
Individual regions can provide their own access restriction dictionaries.

### Interpretation
* `yes` - this kind of vehicle is allowed to drive on this kind of road unless
    tagged otherwise on the individual way (e.g. "motorcar=no").
* `designated` - same as yes but this road can optionally be preferred by some
    of your metrics.
* `no` - this kind of vehicle is not allowed to drive on this kind of road
    unless tagged otherwise on the individual way (e.g. "motorcar=yes").
"""
const ACCESS_RESTRICTION = Dict(
    "access" => Dict(
        "motorway" => :yes,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :no,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :no
    ),
    "motorcar" => Dict(
        "motorway" => :designated,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :no,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :no
    ),
    "motorcycle" => Dict(
        "motorway" => :designated,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :no,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :no
    ),
    "goods" => Dict(
        "motorway" => :designated,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :no,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :no
    ),
    "hgv" => Dict(
        "motorway" => :designated,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :no,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :no
    ),
    "psv" => Dict(
        "motorway" => :designated,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :no,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :no
    ),
    "moped" => Dict(
        "motorway" => :no,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :no,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :no
    ),
    "horse" => Dict(
        "motorway" => :no,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :yes,
        "bridleway" => :designated,
        "cycleway" => :no,
        "footway" => :no
    ),
    "bicycle" => Dict(
        "motorway" => :no,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :no,
        "path" => :yes,
        "bridleway" => :no,
        "cycleway" => :designated,
        "footway" => :no
    ),
    "foot" => Dict(
        "motorway" => :no,
        "motorway_link" => :yes,
        "trunk" => :yes,
        "trunk_link" => :yes,
        "primary" => :yes,
        "primary_link" => :yes,
        "secondary" => :yes,
        "secondary_link" => :yes,
        "tertiary" => :yes,
        "tertiary_link" => :yes,
        "unclassified" => :yes,
        "residential" => :yes,
        "living_street" => :yes,
        "street" => :yes,
        "track" => :yes,
        "service" => :yes,
        "road" => :yes,
        "pedestrian" => :yes,
        "path" => :yes,
        "bridleway" => :no,
        "cycleway" => :no,
        "footway" => :designated
    )
)
